### PR TITLE
Code refactory and UI improvements for MultipleInstances sample

### PR DESCRIPTION
**Pull request by ancirja-m**

### CODE REVIEW

**Review by CesarValiente — APPROVED** [review]
LGTM! Thanks Andrei! :-)

**Comment by bimiron** [comment]
Looks great! Please also update the instrumentation test:)

**Review by bimiron — COMMENTED** [review]
Looks great! Please also update the instrumentation test which uses the old ids:)

**Review by bimiron — APPROVED** [review]

**Review by CesarValiente — APPROVED** [review]
LGTM! Thanks Andrei!

**Pull request merged**
