### PR TITLE
add readmes for all kotlin sample folders

### PR DESCRIPTION
**Pull request by conceptdev**
Add readme file and screenshots for each sample app (task 113725)

### CODE REVIEW

**Review by CesarValiente — APPROVED** [review]
Wops! missed this PR! LGTM! 🚀
Thanks Craig, pretty useful for the samples.

**Comment by CesarValiente** [comment]
@CristianVerdes please, check when you are back ;-)

**Comment by CesarValiente** [comment]
I think that with the new hierarchy scheme after "container app" is being merged (no more sample modules --> packages into main and single app) this branch/PR is outdated and makes no sense to have it. Thoughts?

**Comment by conceptdev** [comment]
if all the individual projects are being deleted then yes we can close this - but if they aren't already deleted no harm in merging?

**Comment by CesarValiente** [comment]
I think this will cause conflicts in the merge they are currently doing, since all folder samples will be deleted, so I think is better if we close this PR without merging. We can enhance the main readme (root folder) with this specific information afterwards.

**Comment by CesarValiente** [comment]
Craig, after conversation with the team and seeing the final code base, we are not getting rid of the modules now (it will be next) so yeah we can merge this PR once that the main one is merged.

**Comment by CesarValiente** [comment]
@microsoft/devx-android-reviewers can you folks please review this PR? Thanks!

**Review by ancirja-m — APPROVED** [review]

**Review by soalb-m — APPROVED** [review]

**Pull request merged**
