### PR TITLE
Apply the new design for Companion Pane

### PR DESCRIPTION
**Pull request by joyl1216**

### CODE REVIEW

**Comment by joyl1216** [comment]
Screenshot_1602798819
Screenshot_1602798825
Screenshot_1602798840
Screenshot_1602798848

**Review by guymerin — APPROVED** [review]

**Comment by guymerin** [comment]
let's have some watermark stating that the controls are mocks and not actually doing anything, otherwise folks will think it's a bug...

**Comment by joyl1216** [comment]
@guymerin 

> let's have some watermark stating that the controls are mocks and not actually doing anything, otherwise folks will think it's a bug...

Do you mean watermark in the image or some text next to the control?

**Comment by guymerin** [comment]
> @guymerin
> 
> > let's have some watermark stating that the controls are mocks and not actually doing anything, otherwise folks will think it's a bug...
> 
> Do you mean watermark in the image or some text next to the control?

I think in the image will be easier and doesn't touch the code.

**Comment by joyl1216** [comment]
> > @guymerin
> > > let's have some watermark stating that the controls are mocks and not actually doing anything, otherwise folks will think it's a bug...
> > 
> > 
> > Do you mean watermark in the image or some text next to the control?
> 
> I think in the image will be easier and doesn't touch the code.

@scorpmel-meshah Can you help me with this?

**Review by Mehul1995 — COMMENTED** [review]
Looks good.

**Comment by Mehul1995** [comment]
Updating with watermarks. Do you have any suggestions for the watermark? Microsoft logo? Surface duo logo?

**Comment by guymerin** [comment]
@Mehul1995 , what I meant with watermarks is not about logo, but to let developers understand that the controls / sliders are mocks and don't actually change the image...

**Review by CesarValiente — APPROVED** [review]
LGTM! :-)

**Comment by joyl1216** [comment]
Screenshot_1602890982
@guymerin Updated image with the watermark. How is that?

**Comment by guymerin** [comment]
The sample water mark is on this image, dev will still think the controls will be usable...

**Comment by Mehul1995** [comment]
Passed on new design changes to Joy!

**Comment by guymerin** [comment]
@Mehul1995 , can we all see it :-)

**Comment by joyl1216** [comment]
@guymerin @Mehul1995 please have a look.
Screenshot_1603414888
Screenshot_1603414921
Screenshot_1603415108
Screenshot_1603415114

**Comment by guymerin** [comment]
it is good.
It is very good
It is very very good

Good job!

**Comment by Mehul1995** [comment]
hahahaha.. I guess I have to figure out a way to make it look less like a movie poster with stamps everywhere.

**Pull request merged**
